version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq:/home:Z
      - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia:Z
      - ./rabbitmq/log/:/var/log/rabbitmq:Z
    ports:
      - "5672:5672"
      - "15692:15692"
      - "15672:15672"
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
