services:
  postgres:
    # see https://hub.docker.com/_/postgres for list of postgres image versions on docker hub
    #image: postgres:latest # To download the latest image
    #image: postgres:17.4-alpine # To download a specific version, here the version 17.4 of Postgresql under an alpine linux distribution
    image: postgres:17.4 # To download a specific version, here the version 17.4 of Postgresql
    container_name: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # HOST_PORT:CONTAINER_PORT
    networks:
      - postgres_network

volumes:
  postgresql_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
