version: '3.9'
services:

  mariadb:
    container_name: mariadb
    image: mariadb:10.7.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=r00t_p@ssw0rd
      - MYSQL_PASSWORD=us3r_p@ssword
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_db
    volumes:
      - ./mariadb/data:/var/lib/mysql