version: "3.8"
services:
    crdb:
        container_name: crdb
        image: cockroachdb/cockroach:latest
        hostname: crdb
        volumes:
            - ./data/crdb:/cockroach/cockroach-data
        command: start-single-node --insecure --http-addr=0.0.0.0:8080 --logtostderr --listen-addr=0.0.0.0
        ports:
            - "26257:26257"
            - "8080:8080"
        networks:
            network_cockroachdb:
                aliases:
                  - crdb

networks:
    network_cockroachdb:
        driver: bridge
