version: '3.9'

services:
  consul:
    container_name: consul
    image: consul:latest
    volumes:
          - ./data/:/consul/data
    command: consul agent -server -bootstrap-expect=1 -data-dir="/consul/data" -ui -client="0.0.0.0" -bind="127.0.0.1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - consul_network

networks:
  consul_network:
    driver: bridge